/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gregtech_api_util_RustUtility */

#ifndef _Included_gregtech_api_util_RustUtility
#define _Included_gregtech_api_util_RustUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gregtech_api_util_RustUtility
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gregtech_api_util_RustUtility_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
